-- Verify stage objects exist (no COPY INTO).

SHOW INTEGRATIONS LIKE 'COMMERCESTREAM_S3_INT';
SHOW STAGES LIKE 'S3_GOLD_STAGE' IN SCHEMA COMMERCESTREAM_DB.RAW;
DESC STAGE COMMERCESTREAM_DB.RAW.S3_GOLD_STAGE;
SHOW FILE FORMATS LIKE 'COMMERCESTREAM_PARQUET_FF' IN SCHEMA COMMERCESTREAM_DB.STAGING;
