-- Verify stage objects exist (no COPY INTO, no LIST @stage).

SHOW FILE FORMATS LIKE 'COMMERCESTREAM_PARQUET_FF' IN SCHEMA COMMERCESTREAM_DB.STAGING;
SHOW INTEGRATIONS LIKE 'COMMERCESTREAM_S3_INT';
SHOW STAGES LIKE 'COMMERCESTREAM_GOLD_STAGE' IN SCHEMA COMMERCESTREAM_DB.STAGING;
DESC STAGE COMMERCESTREAM_DB.STAGING.COMMERCESTREAM_GOLD_STAGE;
