-- Monthly credit cap for project warehouse compute.
-- CREDIT_QUOTA = 3 (~$6 hard cap at ~$2/credit).

CREATE OR REPLACE RESOURCE MONITOR DE_PROJECT_MONITOR
  WITH CREDIT_QUOTA = 3
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE DE_PROJECT_WH
  SET RESOURCE_MONITOR = DE_PROJECT_MONITOR;
