-- Project database and schemas (empty — no tables loaded in guardrails phase).

CREATE OR REPLACE DATABASE COMMERCESTREAM_DB;

CREATE OR REPLACE SCHEMA COMMERCESTREAM_DB.RAW;
CREATE OR REPLACE SCHEMA COMMERCESTREAM_DB.STAGING;
CREATE OR REPLACE SCHEMA COMMERCESTREAM_DB.MARTS;
CREATE OR REPLACE SCHEMA COMMERCESTREAM_DB.MONITORING;
