-- Verification queries — review output after bootstrap.

SHOW WAREHOUSES LIKE 'DE_PROJECT_WH';
SHOW RESOURCE MONITORS LIKE 'DE_PROJECT_MONITOR';
SHOW DATABASES LIKE 'COMMERCESTREAM_DB';
SHOW SCHEMAS IN DATABASE COMMERCESTREAM_DB;
